# Generated by Django 5.1.1 on 2024-09-25 05:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messanger", "0002_delete_message_alter_chat_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiChoiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(max_length=200, verbose_name="Опция")),
            ],
            options={
                "verbose_name": "Опция выбора",
                "verbose_name_plural": "Опции выбора",
            },
        ),
        migrations.AlterModelOptions(
            name="chat",
            options={"verbose_name": "Обращение", "verbose_name_plural": "Обращения"},
        ),
        migrations.RemoveField(
            model_name="chat",
            name="message",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="response",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="user",
        ),
        migrations.AddField(
            model_name="chat",
            name="detailed_description",
            field=models.TextField(
                default=django.utils.timezone.now,
                verbose_name="Ваше описание проблемы, дополнительная информация:",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chat",
            name="emp",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chat",
            name="problem_description",
            field=models.CharField(
                choices=[
                    (
                        "choice1",
                        "Воспроизведение ролика не началось, показалась заглушка",
                    ),
                    (
                        "choice2",
                        "Воспроизведение ролика не началось, видео встало на бесконечную загрузку",
                    ),
                    (
                        "choice3",
                        "Видео воспроизводится рывками, постоянно встает на загрузку",
                    ),
                    (
                        "choice4",
                        "Видео перестало воспроизводиться, показалась заглушка",
                    ),
                    (
                        "choice5",
                        "Воспроизведение ролика остановилось, видео встало на бесконечную загрузку",
                    ),
                    (
                        "choice6",
                        "Выдается сообщение о блокировщике рекламы, но он не установлен на моем устройстве",
                    ),
                    ("choice7", "Другое"),
                ],
                default=None,
                max_length=200,
                verbose_name="Как можно описать возникшую проблему:",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chat",
            name="response_emp",
            field=models.TextField(blank=True, verbose_name="Ответ сотрудника"),
        ),
        migrations.AddField(
            model_name="chat",
            name="response_giga",
            field=models.TextField(
                blank=True, verbose_name="Подсказка-ответ от гигачата"
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Время изменения обращения"
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="user_email",
            field=models.EmailField(
                default=None,
                max_length=100,
                verbose_name="Укажите электронный адрес, по которому мы могли бы связаться для уточнения проблемы:",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chat",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания обращения"
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="multiple_choice",
            field=models.ManyToManyField(
                choices=[
                    (
                        "option1",
                        "Проблема воспроизвелась однократно и больше не повторяется",
                    ),
                    ("option2", "Проблема воспроизводится в другом браузере"),
                    (
                        "option3",
                        "Вы используете программное обеспечение для блокировки нежелательной рекламы",
                    ),
                    ("option4", "Вы используете  антивирус"),
                    ("option5", "Вы подключены к сети через прокси-сервер"),
                ],
                to="messanger.multichoiceoption",
                verbose_name="Укажите утверждения, подходящие к описываемой проблеме:",
            ),
        ),
    ]
