# Generated by Django 5.1.1 on 2024-09-25 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messanger", "0003_multichoiceoption_alter_chat_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="emp",
        ),
    ]
