# Generated by Django 5.1.1 on 2024-09-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messanger", "0004_remove_chat_emp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="multiple_choice",
            field=models.ManyToManyField(
                to="messanger.multichoiceoption",
                verbose_name="Укажите утверждения, подходящие к описываемой проблеме:",
            ),
        ),
    ]
