# Generated by Django 5.1.1 on 2024-09-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messanger", "0005_alter_chat_multiple_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="chat_number",
            field=models.PositiveIntegerField(default=0, verbose_name="ID обращения"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chat",
            name="chat_status",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Статус обращения"
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="problem_description",
            field=models.CharField(
                choices=[
                    (
                        "Воспроизведение ролика не началось, показалась заглушка",
                        "Воспроизведение ролика не началось, показалась заглушка",
                    ),
                    (
                        "Воспроизведение ролика не началось, видео встало на бесконечную загрузку",
                        "Воспроизведение ролика не началось, видео встало на бесконечную загрузку",
                    ),
                    (
                        "Видео воспроизводится рывками, постоянно встает на загрузку",
                        "Видео воспроизводится рывками, постоянно встает на загрузку",
                    ),
                    (
                        "Видео перестало воспроизводиться, показалась заглушка",
                        "Видео перестало воспроизводиться, показалась заглушка",
                    ),
                    (
                        "Воспроизведение ролика остановилось, видео встало на бесконечную загрузку",
                        "Воспроизведение ролика остановилось, видео встало на бесконечную загрузку",
                    ),
                    (
                        "Выдается сообщение о блокировщике рекламы, но он не установлен на моем устройстве",
                        "Выдается сообщение о блокировщике рекламы, но он не установлен на моем устройстве",
                    ),
                    ("Другое", "Другое"),
                ],
                max_length=200,
                verbose_name="Как можно описать возникшую проблему:",
            ),
        ),
    ]
