# Generated by Django 5.1.1 on 2024-09-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messanger", "0006_chat_chat_number_chat_chat_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="chat_number",
            field=models.PositiveIntegerField(default=0, verbose_name="ID обращения"),
        ),
    ]
