# Generated by Django 5.1.1 on 2024-09-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MultiChoiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="FormResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100,
                        verbose_name="Укажите электронный адрес, по которому мы могли бы связаться для уточнения проблемы:",
                    ),
                ),
                (
                    "problem_description",
                    models.CharField(
                        choices=[
                            (
                                "choice1",
                                "Воспроизведение ролика не началось, показалась заглушка",
                            ),
                            (
                                "choice2",
                                "Воспроизведение ролика не началось, видео встало на бесконечную загрузку",
                            ),
                            (
                                "choice3",
                                "Видео воспроизводится рывками, постоянно встает на загрузку",
                            ),
                            (
                                "choice4",
                                "Видео перестало воспроизводиться, показалась заглушка",
                            ),
                            (
                                "choice5",
                                "Воспроизведение ролика остановилось, видео встало на бесконечную загрузку",
                            ),
                            (
                                "choice6",
                                "Выдается сообщение о блокировщике рекламы, но он не установлен на моем устройстве",
                            ),
                            ("choice7", "Другое"),
                        ],
                        max_length=200,
                        verbose_name="Как можно описать возникшую проблему:",
                    ),
                ),
                (
                    "detailed_description",
                    models.TextField(
                        verbose_name="Ваше описание проблемы, дополнительная информация:"
                    ),
                ),
                (
                    "multiple_choice",
                    models.ManyToManyField(
                        to="rutubesupportmain.multichoiceoption",
                        verbose_name="Укажите утверждения, подходящие к описываемой проблеме:",
                    ),
                ),
            ],
            options={
                "verbose_name": "Резюме кандидата (версия 2)",
                "verbose_name_plural": "Резюме кандидатов (версия 2)",
            },
        ),
    ]
