# Generated by Django 5.1.1 on 2024-09-24 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rutubesupportmain", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formresult",
            options={"verbose_name": "Форма", "verbose_name_plural": "Формы"},
        ),
    ]
