# Generated by Django 5.1.1 on 2024-09-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rutubesupportmain", "0002_alter_formresult_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formresult",
            name="multiple_choice",
            field=models.ManyToManyField(
                choices=[
                    (
                        "option1",
                        "Проблема воспроизвелась однократно и больше не повторяется",
                    ),
                    ("option2", "Проблема воспроизводится в другом браузере"),
                    (
                        "option3",
                        "Вы используете программное обеспечение для блокировки нежелательной рекламы",
                    ),
                    ("option4", "Вы используете  антивирус"),
                    ("option5", "Вы подключены к сети через прокси-сервер"),
                ],
                to="rutubesupportmain.multichoiceoption",
                verbose_name="Укажите утверждения, подходящие к описываемой проблеме:",
            ),
        ),
    ]
