# Generated by Django 5.1.1 on 2024-09-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rutubesupportmain", "0003_alter_formresult_multiple_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formresult",
            name="multiple_choice",
            field=models.ManyToManyField(
                choices=[
                    (
                        "Проблема воспроизвелась однократно и больше не повторяется",
                        "Проблема воспроизвелась однократно и больше не повторяется",
                    ),
                    (
                        "Проблема воспроизводится в другом браузере",
                        "Проблема воспроизводится в другом браузере",
                    ),
                    (
                        "Вы используете программное обеспечение для блокировки нежелательной рекламы",
                        "Вы используете программное обеспечение для блокировки нежелательной рекламы",
                    ),
                    ("Вы используете  антивирус", "Вы используете  антивирус"),
                    (
                        "Вы подключены к сети через прокси-сервер",
                        "Вы подключены к сети через прокси-сервер",
                    ),
                ],
                to="rutubesupportmain.multichoiceoption",
                verbose_name="Укажите утверждения, подходящие к описываемой проблеме:",
            ),
        ),
    ]
