# Generated by Django 5.1.1 on 2024-09-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rutubesupportmain", "0004_alter_formresult_multiple_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formresult",
            name="multiple_choice",
            field=models.ManyToManyField(
                to="rutubesupportmain.multichoiceoption",
                verbose_name="Укажите утверждения, подходящие к описываемой проблеме:",
            ),
        ),
    ]
