# Generated by Django 5.1.1 on 2024-09-25 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rutubesupportmain", "0006_alter_formresult_multiple_choice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FormResult",
        ),
        migrations.DeleteModel(
            name="MultiChoiceOption",
        ),
    ]
